name: PGATS AUT-WEB

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # Clone do projeto para a máqui
      - uses: actions/checkout@v4

      #Conferir a versão instalada
      - name: Node version
        run: node --version

      - name: Instalando dependências
        run: npm install

      - name: Executando os testes do trabalho final
        run: npm run test:trabalho-final

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos
